### ISSUE TITLE
Multi server granting when online

### ISSUE THREAD

**Issue by Blocksnmore** [CraftingStore/Suggestions#224]
Hello, i would like to request that there is a feature where under the when should the command be run feature to have „Run when online in each server” so i can decide if its a package that is given in one server or in all of the servers selected under the category. Thanks

**Comment by Tim-NL** [comment]
Hi,

We've decided to not include this feature. We have commands that can be set to "require online", this will execute this command only when the user is online on that server. Allowing to execute the command on all servers, when the user is on just one of them, would make configuring packages very hard and complex for store owners. Due to the fact that this request was not done outside of this one, we don't think that the demand for it, matches the amount of work and complexity for store owners involved.

Thanks for adding your suggestion!

-Tim
