### ISSUE TITLE
[Feature Request] Add MercadoPago gateway

### ISSUE THREAD

**Issue by M4T14SG4M3R** [CraftingStore/Suggestions#309]
**Is your feature request related to a problem? Please describe.**
I want to suggest to add MercadoPago gateway system

**Describe the solution you'd like**
MercadoPago is similar to Paygol and Paymentwall but it accept every credit card including virtual credit cards and bank deposit in all south america countries including Mexico

**Additional context**
Tebex has it and it's been ok since they added it, i would like to have it on CS

**Comment by plebexer** [comment]
ojala lo agregen xd

**Comment by LinsaFTW** [comment]
Me uno. La API parece ser muy facil de implementar y ayudaria a recibir muchas mas compras de forma simple.

**Comment by Tim-NL** [comment]
Hi,

I've been looking into their service, but I have a few issues;
- Most of the text is unreadable for me, their API docs are Englisch, so that will help a lot.
- I'm unable to create a test account, as I do not have the required information (as I do not live in one of the supported countries)
- We cannot use their SDK, it is not supported on the platform that we use. Thus we'll need to manually create the integration, directly using their API & IPN. (that's fine, but it will make the process harder).

Every contact page I see requires me to log-in. Would any one of you be able to provide me with credentials for their sandbox environment, if they have any? If so, please mail at tim@craftingstore.net. - Do not email if these are production details, or if you are using the same password anywhere else. I just need an account to test with, but it may not be used in production, or linked to a bank account or something. 

-Tim

**Comment by Tim-NL** [comment]
Hi,

We have decided to work on implementing PagSeguro, I think it is very similar to the one requested here. 

Please see !381 for updates. 

-Tim

**Comment by plebexer** [comment]
i think that pagseguro is only for brasil

**Comment by plebexer** [comment]
i wanted to help with the mercadopago issues you had but i dont have an account to give to you, but i can try creating one

**Comment by LinsaFTW** [comment]
> Hi,
> 
> We have decided to work on implementing PagSeguro, I think it is very similar to the one requested here.
> 
> Please see #381 for updates.
> 
> -Tim

No. Thats a big mistake; MercadoPago is the biggest south american payment company and gives access to country-specific payment methods and thats the only reason why i am asking for MercadoPago instead of PagoSeguro or BoaCompra.
