### ISSUE TITLE
Can not buy if they brought another package suggestion

### ISSUE THREAD

**Issue by ghost** [CraftingStore/Suggestions#311]
**Is your feature request related to a problem? Please describe.**
Yes. Because when I enable cumulative people who brought the higher ranks can get the lower ranks for free. And this makes it so they can regain advantages from lower ranks and keep buying them.

**Describe the solution you'd like**
Add an option in the package editor under requirements, an option to do the opposite.
"Do not allow if the player brought package..."

Or add a option to instead of making lower prices free when cumulative is on just remove it instead

**Comment by Tim-NL** [comment]
Hi,

I'm not sure why this happens for you, but this is not what cumulative packages do. It will disable them, and you won't be able to buy them when they've already bought them.

I'll close the issue if you still have this issue, please create a support ticket instead, because I think that it might be limited/ related to your specific store.

-Tim
