### ISSUE TITLE
Blind copy of the receipt to another email

### ISSUE THREAD

**Issue by ivenassenkamp** [CraftingStore/Suggestions#315]
**Is your feature request related to a problem? Please describe.**
Blind copy to another email, to collect the bills for e.g. a tax advisor

**Describe the solution you'd like**
Add a field where you can choose which email a blind copy will be sent to

**Additional context**
-

**Comment by Tim-NL** [comment]
The receipts are only a confirmation to the buyer that they will receive their items. It is not a receipt that can be used for tax. As it does not contain the required information on there.

**Comment by ivenassenkamp** [comment]
Ok, but a general function that you get the payment by email again would be very helpful

**Comment by Tim-NL** [comment]
We'll decline the request at this point in time, you can enable payment notifications from [ Profile -> Notifications ]. This will not be a direct copy of the receipt mail, but it is meant to be that way because the receipt is only for the client. You can find all information in the dashboard.

-Tim
