### ISSUE TITLE
Up the limit for image upload on our store design

### ISSUE THREAD

**Issue by LiamBinLaden** [CraftingStore/Suggestions#38]
We're currently too limited, upping it will greatly help everyone - especially users wanting to apply GIFs or 4K backgrounds.

**Comment by Tim-NL** [comment]
Hello,

CraftingStore is not a CDN to host your images & content, if you require 4k images, please use a CDN, and link the image directly from there into your CraftingStore design. Our editor does fully support this. 

We did not receive any complains about the image limits, as it's high enough for any reasonable image.

~Tim

**Comment by LiamBinLaden** [comment]
I had many problems uploading images especially for a background, it's the reason why I made this suggestion. Also how do we use a CDN on the free plan?

**Comment by Tim-NL** [comment]
If you're image is to big, you can use any online compressor. Storing images is costing us money, because we need to store them on our CDN server. We offer around 200MB per user in total to store images. 

Using images that are 4k of bigger then 2MB will only cause your store to load much slower, images of those sizes are really not suitable for the web, you should not have images bigger then 1MB if you want a fast website. 

And you can order a hosting package somewhere and upload the images there, or use imgur to store them.

~Tim
