### ISSUE TITLE
Add Payment Gateways to "Brazil"

### ISSUE THREAD

**Issue by luiswenner** [CraftingStore/Suggestions#381]
**Is your feature request related to a problem? Please describe.**
Need to add payment methods to Brazil, which would make the platform highly compatible and thus reach more customers

**Describe the solution you'd like**
By creating payment methods for the main receiving companies in the country, it could attract an even larger audience to the community, thus making the country compatible and available to enjoy all the possibilities and tools.
there are currently three main payment paths for brazil
1- PagSeguro
2- MercadoPago
3- Boleto Bancario
4- PicPay (Less Expressive)

**Additional context**
There is great support for developers and ease to create APIs without complications.
1- https://dev.pagseguro.uol.com.br/
2- https://www.mercadopago.com.br/developers
3- 'The above methods have support for payments in the form of a bank slip'
4- https://ecommerce.picpay.com/doc/

**Comment by Rodaviva29** [comment]
Olá, luiswenner! 
Você pode usar esses primeiros 3 métodos de pagamento através do Payment Wall uma ferramenta que a CraftingStore disponibliza para se receber os pagamentos. Espero ter ajudado. Bom fim de semana.

**Comment by Tim-NL** [comment]
Hi,
@luiswenner & @dabou0

I've tried to contact PagseGuro because I cannot sign up for their sandbox account using my Dutch phone number. I explained what I wanted to do (not use their service myself, but offer it to clients as a gateway). And they explained that I won't be able to use my phone number.

After that reply, I requested an account, just to test, and explained again what CraftingStore is exactly. I have not gotten any response just yet, and that was about 3 days ago. 

I'm having trouble reading the pages, as they are all in languages that I cannot understand. So; is a sandbox account just a testing account that can do nothing more than that? And if it is, would one of you allow me to use one of your test accounts to see if we can implement them as a payment method?

If so, please let me know by emailing me at tim@craftingstore.net.

-Tim

**Comment by dabou0** [comment]
i've emailed you and provided info.

**Comment by Tim-NL** [comment]
Hi all,

We've implemented these two;
1- PagSeguro
2- MercadoPago

PagSeguro has been implemented some time ago (few weeks) and MercadoPago has just been added. Thanks for the suggestion. And thanks to @dabou0 for providing testing information & helping with questions that we had. 

-Tim
