### ISSUE TITLE
MultiLinee Message

### ISSUE THREAD

**Issue by devttodgers** [CraftingStore/Suggestions#384]
**Is your feature request related to a problem?** 
No, but it's very sad to see a normal link white... It's a really cool thing to see a multilinee text with a link :)

**Describe the solution you'd like:** 
that or i can use \n to go in a new line or something like description, so that you can go to a new line only pressing Enter for the in-game click message

Cattura

**Comment by Tim-NL** [comment]
Hi,
Your suggestion is not using the format as described in our README; https://github.com/CraftingStore/Suggestions/blob/master/README.md

https://github.com/CraftingStore/Suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

Please update your suggestion to comply with this format, and mention me when this has been done. For now, I'll close your issue, because it does not follow our rules.

-Tim

**Comment by devttodgers** [comment]
Is your feature request related to a problem? No, but it's very sad to see a normal link white... It's a really cool thing to see a multilinee text with a link :)

Describe the solution you'd like: that or i can use \n to go in a new line or something like description, so that you can go to a new line only pressing Enter

![Cattura](https://user-images.githubusercontent.com/54081934/89889940-d0262f80-dbd2-11ea-9524-0a6f2917de22.PNG)

**Comment by devttodgers** [comment]
@Tim-NL

**Comment by Tim-NL** [comment]
Hi,

Implemented. You can now use \n to make a newline.

-Tim
