### ISSUE TITLE
Cooldown Placeholder

### ISSUE THREAD

**Issue by LixelTV** [CraftingStore/Suggestions#419]
Hello, I have a feature idea: It would be great if there is a placeholder for the homepage that shows a countdown when a sale ends.  E.g. {countdown_sale_NAME}.  what is there when it has expired you should be able to adjust.  there should also be a function to time-limit products and then get a placeholder.  In addition, you should be able to activate that a countdown is displayed at the point where the name is and the icon is shown.  in the product list.

**Comment by Tim-NL** [comment]
Hi,

After looking into this feature, we've decided to not implement this. Due to the way the stores are cached, it is not really possible for us to do dynamic things like counters. The cache for the modules, etc, is cleared when updates are made to them. But something as real-time as a counter is not possible.

-Tim
