### ISSUE TITLE
Discord Store Idea

### ISSUE THREAD

**Issue by MrStickManSam** [CraftingStore/Suggestions#423]
**Is your feature request related to a problem? Please describe.**
Not related to a problem but an idea for the Discord bot.

**Describe the solution you'd like**
A way to have a Discord store that is not connected to a Minecraft server would be really useful. You could add a way to login with Discord when at checkout instead of a Minecraft name. After the package is purchased the bot will then do what the package Discord tab does now.

**Additional context**
No further info.

**Comment by Tim-NL** [comment]
Hi,

After looking into this, we've decided to not offer this as a specific use-case for our platform. Because you can already achieve this without any real modifications. 

You'd just need to modify the text "Minecraft name" to "Display name" or something like that. This name will not really be used for anything. We have recently introduced the "Login with Discord" option.

In this case, you can simply create a Discord server, and not add any normal commands. Then I think you'll achieve exactly what you want.

More information about our new Discord integration: https://help.craftingstore.net/books/general/page/discord-integration

-Tim
