### ISSUE TITLE
Gift-card should be used as Payment or Second Coupon code and not as Coupon-code

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#436]
**Is your feature request related to a problem? Please describe.**
I'm migrating from Tebex and it frustrates me that Gift-card is used as some sort of coupon code: you cant use both, its one or another. Player has a 25% off coupon code and some money left on his Gift-card? Too bad: its either 25% off and pay with paypal or whatever OR use gift-card code and forget about 25% Off. 

**Describe the solution you'd like**
Gift-card should be used as a payment solution. Add package, apply coupon code, pay with Gift-card if enough
balance (or apply as second coupon code = same result) if not use paypal or whatever. 
I mean, when you get a gift-card in a real shop (irl) you don't expect to lose on a coupon code discount or a sale, right?

**Additional context**
![image](https://user-images.githubusercontent.com/74799262/99865126-b69f6700-2b75-11eb-81e1-f24280ff3a91.png)

**Comment by Tim-NL** [comment]
Hi,

I do understand your concern, and you are correct. However, this is something that is baked into the system from the start, and was by design back then. 

Changing this will require us to redo the whole basket system from the ground up. This is not something we think is worth the time <> benefit ratio. In the last few years, we never had any requests about this, thus we believe that the demand for it is pretty minor, and is not worth spending weeks of work on. Sorry.

-Tim

**Comment by 2ic** [comment]
I understand.. thank you
