### ISSUE TITLE
mod console post when delivering packages.

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#438]
**Is your feature request related to a problem? Please describe.**
Need more verbose mod; right now derived packages only shows delivered on the crafting store.

**Describe the solution you'd like**
in-console only :
(11:05:17) | [CraftingStore] Processed online command for 765611981988855222: inventory.giveall supply.signal
(11:05:17) | [ServerVar] giving Spoonn 1 x Supply Signal
(11:05:17) | [ServerVar] giving 2IC 1 x Supply Signal
(11:05:17) | [ServerVar] giving Lague 1 x Supply Signal
(11:05:17) | [ServerVar] giving DrOx 1 x Supply Signal
(11:05:17) | [ServerVar] giving Ston 1 x Supply Signal

**Additional context**
Really helpful for admins to confirm packages delivery in-game + it's part of server logs.

**Comment by Tim-NL** [comment]
Hi,

Would you be able to share what plugin/integration you are using? Some of our plugins have a debug mode, that will show more information. And others do not. To find out if you can enable it, requires us to know what platform you're on.

-Tim

**Comment by 2ic** [comment]
Rust platform    [Info("Crafting Store", "CraftingStore", "0.1.4")]


and my JSON config file : 
{
  "frequencyMinutes": 5,
  "token": "***************************************************"
}

**Comment by Tim-NL** [comment]
Hi,

Our Rust integration does not offer the ability to notify the user, and we do currently not plan on adding verbose information in the plugin there.

The reason for this being, that it is unnecessary extra "spam" in the console because the only way that the commands are marked as "completed" on our dashboard, is when the Oxide plugin notifies our endpoint about the command being executed. So if it is set to complete at our end, then it was executed.

-Tim
