### ISSUE TITLE
Gift Card Duplication

### ISSUE THREAD

**Issue by LattyPvP** [CraftingStore/Suggestions#442]
**Is your feature request related to a problem? Please describe.**
Feature Request

**Describe the solution you'd like**
Add a way to "duplicate" gift cards this way store owners can create a gift card as a template and then just duplicate that so they won't have to keep making the same settings for every new gift card.

**Comment by 2ic** [comment]
When you setup 1st Gift-card card you can make it as a template. Just Enable this package? OFF
After that you can duplicate. Hopefully this helps.
![image](https://user-images.githubusercontent.com/74799262/99867684-8cf03b00-2b89-11eb-84f8-a1b2d1c80131.png)

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion.

You can now duplicate gift-cards, it will keep the settings but change the coupon code.

-Tim

**Comment by 2ic** [comment]
> Hi,
> Thanks for the suggestion.
> You can now duplicate gift-cards, it will keep the settings but change the coupon code.
> -Tim

I'm curious how can you use it this way; duplicating Gift-cards only gives you codes.. There's noway you can follow-up on those when you're past dozen or so.. That's why I prefer those created by a package. Hopefully Tim will implement my latest suggestion when Gift-cards are created with a package.
