### ISSUE TITLE
Option on package creation to make it available for purchase only when {serverpop} condition is met (min serverpop: 20) 

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#459]
**Is your feature request related to a problem? Please describe.**
Players often purchase package for whole server; I would like to limit some OP packages to a server pop condition.

**Describe the solution you'd like**
Option on package creation to make it available for purchase only when {serverpop} condition is met (min serverpop: 20) 

**Additional context**
something like this:
![image](https://user-images.githubusercontent.com/74799262/100463634-2479f000-309a-11eb-9cf9-999a33e3462c.png)

**Comment by Tim-NL** [comment]
Hi,

Would you be able to explain what "Server population" is exactly?

-Tim

**Comment by 2ic** [comment]
How many players are playing on a specific server.

**Comment by Tim-NL** [comment]
Hi,

This is not information that we know, we do not take stats from the server. And we believe that this will not benefit lots of stores. We'll have to decline this request. Sorry.

-Tim

**Comment by 2ic** [comment]
Maybe not lots but a nice option to have.. oh well.

**Comment by Tim-NL** [comment]
It is a nice option to have for sure, but implementing this requires updates to; The plugin, the API, the Dashboard, and the front-end shop. While only a few shops will use this feature. As it is not something that most would be looking for I think. I cannot really think of any good use-cases for this feature.

Thus spending development hours on this feature, instead of others, is not worth it in my opinion. 

-Tim

**Comment by 2ic** [comment]
I understand.. Setting a time schedule for some packages would be easier to implement?
