### ISSUE TITLE
Stackable Payment expiration on multiple of same package purchased

### ISSUE THREAD

**Issue by MageAtoru** [CraftingStore/Suggestions#494]
**Is your feature request related to a problem? Please describe.**
We where looking for an option to stack "Monthly Minecraft Ranks" and "Monthly Discord Roles" by using the inbuilt Payment expiration option
- now in Minecraft this is not a problem since plugins can handle expiration and stacking of multiple command / rank expiration times
- with Discord as we found out if a player purchases 2 x Monthly Role the role would be removed after 1 month and not 2 since both items purchased run at same time instead of stacking

**Describe the solution you'd like**
- Toggle option for enabling payment expiration stacking
- if enabled: user purchases 2 x Monthly package, when 1st month expires second one starts giving user 2 months before he looses the package

**Additional context**
- we see this feature being most usable in Discord for timed roles (monthly ranks...)

**Comment by EffeDion** [comment]
Would love this one, As of now its already pretty good with the subscriptions. But this would be a really usefull feature aswell.

**Comment by Tim-NL** [comment]
Hi,

After going through the suggestions I noticed this once.

We actually already do exactly this. If a package with an expiration date is bought again, it will extend the first one, and run the renewal commands instead of the initial ones. I'm not sure if we already did this when this suggestion was made, but now we do for sure.

-Tim
