### ISSUE TITLE
Reset Goal Button

### ISSUE THREAD

**Issue by w41k3r26** [CraftingStore/Suggestions#504]
Every month when i want to check on the sales or want to make changes, I need to make a payment before I can see the donation goal reset.

A very easy solution would be adding a "Reset" button to the dashboard which will open every month only for 1-time use to reset the donation goal to 0%. Also if the donation goal is automatically reset, it should remain disabled.

This would help in getting clear info on the donation goal for the current month and players wanting to donate to the server seeing that there have been 0% donations for the current month.

This could also be implemented in the plugin placeholders.

**Comment by Tim-NL** [comment]
Hi,

After some digging, I found out that we do reset the goal every month, but due to caching, it will not always show the correct value when no new payments are created. We'll look into a way to solve this. For now, you can just go to [ Pages -> Homepage ] and click "save" this will clear the homepage cache, thus clearing the goal as well.

-Tim
