### ISSUE TITLE
If basketToken cookie is not set, adding a coupon returns to home page

### ISSUE THREAD

**Issue by Kopo942** [CraftingStore/Suggestions#527]
**Describe the bug**
Title pretty much says it: if the user clicks the redeem coupon button and a `basketToken` cookie hasn't been set in browser memory, whether there is a code or not in the form and whether the code is valid or not, the browser returns to the shop's homepage without any error given to the user.

More technically, when the `basketToken` cookie is not provided in the request, the API for some reason returns the base URL of the store in the `location:` header, which in turn makes the browser do the redirect to the home page.

**To Reproduce**
1. Enter incognito mode or clear cookies for `example.craftingstore.net`
2. Go to https://example.craftingstore.net/checkout/basket 
3. Click on "Redeem" (doesn't matter if you input a code or not)
4. Notice the browser redirecting to the home page without an error message
5. Go to https://example.craftingstore.net/package/493, enter random username and click "Add to cart"
6. Click on "Redeem" (doesn't matter if you input a code or not)
7. Notice the browser staying on the same page

**Expected behavior**
When adding a coupon but nothing has been added to the basket, the store should not redirect the user to the home page, but instead:
1. Set the basketToken cookie and 1) add the coupon if it's valid or 2) show an error message if the coupon is not valid
**OR**
2. Prompt the user to add an item in the basket before allowing them to add a coupon (Tebex implements this by simply not allowing the user to enter their basket via button/link if there's nothing in there. I would prefer this option.)

**Platform**
Any  CraftingStore webstore (only tested in Minecraft stores)

**Additional context**
There seems to be a general lack of error messages and fail-fast functionality in the store, including this one. Going to gather some more bugs and post them later.

**Comment by Tim-NL** [comment]
Hi,

The specific bug you are describing now is not really a bug, but by design. The user cannot do anything on the shopping basket when they are not logged in (so when there is no token cookie just yet). So it redirects them back to the store homepage, so they can add some items to their basket.

If they already have items, or when they are already logged in, then they can add coupons/gift-cards just fine, and it will show them.

Thanks for your extensive report, but this is expected behavior, and by-design.

-Tim
