### ISSUE TITLE
Bitcoin Payments automatically using Blockgate.io

### ISSUE THREAD

**Issue by Manfruity** [CraftingStore/Suggestions#534]
**Is your feature request related to a problem? Please describe.**
I would love to see automatic bitcoin payments to be available and my suggestion is add blockgate.io to payment gateway

**Describe the solution you'd like**
Automatic bitcoin payments

**Comment by Tim-NL** [comment]
Hi,

We decided to implement crypto using Coinbase Commerce. You can enable it from our dashboard, you can accept Bitcoin through them.

The provided payment provider (blockgate.io) looks pretty weird, they have only existed since 2020 and everything gives an "In beta" notice. That is not something that we want to use for processing payments. 

-Tim
