### ISSUE TITLE
Hosting own bot (Discord Integration)

### ISSUE THREAD

**Issue by itsWarHammer** [CraftingStore/Suggestions#545]
**Is your feature request related to a problem? Please describe.**
I would like to host my own bot for discord integration

**Describe the solution you'd like**
Allow us to somehow give roles and other discord integration stuff using our own bots instead of CraftingStore's own bot

**Additional context**
None

**Comment by Tim-NL** [comment]
Hi,

This is not something that we are going to support at this point in time.

Our bot fetches the roles it needs to issue from our global API, and it contains all pending roles, regardless of server. From there, we'll give out the roles on the correct Discord servers, and then we notify our API that the roles were given.

We need to know to what user, and on what server a role was issued. Because we also support taking away roles after they have been given. Allowing random bots to handle this data may give us incorrect data (because we have no way to check if what you are giving us, is correct).

When our bot notifies us that, for example, a claim command was issued on a specific Discord server (by its ID) we know for a fact that it is correct. When your bot tells us; I just processed role with ID X, on guild ID Y, then we have no way of knowing that it is correct. We also have no way of validating that you own the server, because without our bot there is no way for us to verify it at all.

So this is not possible for us to support without introducing many security risks.

-Tim
