### ISSUE TITLE
Bug report - Paypal transaction ID's do not match (Business integration)

### ISSUE THREAD

**Issue by Bxrde** [CraftingStore/Suggestions#547]
**Describe the bug**
The external ID's in CraftingStore do not match the PayPal transaction codes, making it impossible go get the money.
The account will be closed, if I cant solve this problem.

**To reproduce**
Go to a payment from my store and compare it the PayPal transactions.

**Expected behavior**
Having matching ID's.

**Screenshots**
<snip>

**Platform**
CraftingStore.

**Additional context**
I have to do my taxes.

**Comment by Tim-NL** [comment]
Hi,

Thanks for adding it, I removed your screenshots, because Github issues are public, having the screenshots with a legal name in there is not really "safe". We have enough information without them.

Do know that if we add the public-facing transaction ID in there, instead of PayPal's internal one, it won't affect old payments, just new ones. So you should be able to look the payments up by date (you can do that at the transactions section at PayPal).

-Tim

**Comment by Bxrde** [comment]
And what about the old payments?

**Comment by Tim-NL** [comment]
Hi,

You can search them by date.

I checked, and the ID that you are seeing is the order ID, their orders API does not provide us with the transaction ID at all; https://developer.paypal.com/docs/api/orders/v2/#orders_capture

So it seems like we cannot get it. The thing you see, is the reference to the paid-for order. But not the public-facing transaction ID, because we cannot get it from their API.

-TIm
