### ISSUE TITLE
Add new items to list for in-game display

### ISSUE THREAD

**Issue by gecko10000** [CraftingStore/Suggestions#576]
**Is your feature request related to a problem? Please describe.**
I'd like to use netherite and copper blocks in the /buy GUI, but only blocks up to 1.13 are available.

**Describe the solution you'd like**
A refresh of the items available on CraftingStore (and ideally none of the materials that are not items: TRIPWIRE, POTATOES, etc.)

**Comment by levtey** [comment]
Can we get this moving? It doesn't seem to be too difficult to implement. Alternatively, it would be a good long-term solution to change the list to a fill-in-the-blank box, so new items can be used in newer versions without requiring an update.

**Comment by Tim-NL** [comment]
Hi,

It is a bit harder than you describe it to be. Because our plugin supports 1.8 -> 1.17 we need to layer between it to support different blocks. Mojang changed their naming schema from IDs to names a while back (around 1.12 or something). 

If you can supply me with a list of all native block names and their human readable names in the following format;

'STONE' => 'Stone',
'GOLD_BLOCK' => 'Gold Block',

Then that would be great, and we can simply import it easily into our dashboard.

-Tim

**Comment by levtey** [comment]
I see. Looking at the Material class, it seems there is a deprecated method to getMaterial using the item ID. Therefore, it should be as simple as `version < 1.13 ? Material.getMaterial(Integer.parseInt(input)) : Material.getMaterial(input.toUpperCase())`. Another option is to use the XMaterial library to add cross-version support, I've seen many plugins use it. In any case, I do think the best way to do this going forward is by allowing players to fill in what they need, so that a list of all materials doesn't need to be generated every version to add support for new items.

**Comment by Tim-NL** [comment]
We can add an "other" option that allows you to type it yourself for sure. 

-Tim

**Comment by levtey** [comment]
That might be the best way to do it.

**Comment by Tim-NL** [comment]
Hi,

I never updated this suggestion but;

it is now possible to choose "Custom" and it will allow you to enter a custom icon name like; `STONE`.

-Tim
