### ISSUE TITLE
Language: Add separate options for "Buy now" and "select username"

### ISSUE THREAD

**Issue by KickSquareMC** [CraftingStore/Suggestions#585]
**Is your feature request related to a problem? Please describe.**
When players select a category that has cumulative packages enabled and they are not signed in, they are prompted to enter their username. Instead of "Done" or "Select username", though, it says "buy now", which might worry some potential customers that they're buying something when they're really just inputting their username. I decided to go to the language settings and change "Buy now" to "Select". Unfortunately, this also affected the "Buy now" when you have a package selected (which should stay buy now)

**Describe the solution you'd like**
Add separate language options for "select username" and "buy now"

**Additional context**
KickSquare#7689 on discord if you have any questions (I'm in the discord server)

**Comment by Tim-NL** [comment]
Hi,

You can modify these with our Silver plan. We offer some customizability using the language page, but if you require very specific things, you'll need to change it in the template.

The reason it says "Buy Now" is because some payment gateways actually require this, or they won't accept your site. 

-Tim
