### ISSUE TITLE
Quantity specification not changeable for products with user limit

### ISSUE THREAD

**Issue by ledxmme** [CraftingStore/Suggestions#592]
**Describe the bug**
If you change the quantity in the shopping cart of a product with user limit, the quantity will not be updated with a click on refresh. I think this is a bug, because you should be able to buy at least the quantity still available for the user.

**To Reproduce**
1. Select a package with a user limit
2. Add this package to basket
3. Change amount of package higher than 1
4. Click on update
5. The amount was not changed

**Expected behavior**
The quantity is not updated and remains at 1.

**Screenshots**
No screenshot but video: https://www.youtube.com/watch?v=-cCIdHV9Sak

**Platform**
The CraftingStore shop website.

**Additional context**
This text has been machine translated.

**Comment by Tim-NL** [comment]
Hi,

Thanks for your report.

This is by design, because of the possibility of abuse, we only allow one item at a time for packages with a user limit. This is not something that we are going to change currently. I think your template does not display it correctly, as it should not show or disable the quantity box as a whole, so it is clear that it is disabled.

-Tim
