### ISSUE TITLE
CraftingStore Wallet

### ISSUE THREAD

**Issue by alexxdevv** [CraftingStore/Suggestions#605]
**Describe the solution you'd like**

Create CraftingStore Wallet, all payment methods will go to that wallet and they can be exported to paypal or bank account whenever you want.
In this way you can have multiple payment methods and be able to export them all to the payment method you want, without having to register on the official website of each payment method.

Everything much more comfortable!

**Comment by Tim-NL** [comment]
Hi,

We are not planning to implement handling money like that at this point in time. Currenlty, money is handled by payment gateways (e.g. Stripe) that are huge and have certifications and the know-how to handle tax for those payments.

If we'd receive money on your behave, we'd have to;
- Deal with the taxes for every country in the world, and file on your behave.
- Deal with charge-backs
- Deal with the liability of actually processing the money, instead of having the professionals handle it. 

Implementing this will be way too much liability and responsibility to take at our size. We'd need a team dedicated to this part to take care of it, and we simply don't have to resources to do this. 

-Tim
