### ISSUE TITLE
Add a point system, enjin CMS donationcraft has a point system where you can give players points to use on your store

### ISSUE THREAD

**Issue by MODKILLER1001** [CraftingStore/Suggestions#649]
**Is your feature request related to a problem? Please describe.**
Enjin CMS is nearing its end time now. There are no other solutions with points

**Describe the solution you'd like**
Add a way to give points in game via a command for a player to use on the store, maybe have them type a command in game to get a code to authenticate with on the store

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion.

There are a few options that we have that are sort of like this - But not exactly the same;

1) Gift-cards:
You can give users gift-cards and have players pay with those.

2) In-game currency
Some time ago we added a feature where users could pay with in-game currency on Minecraft servers. That may help?

We are not really looking into adding a currency of our own and keeping track of user wallets on our platform. Enjin can do that because they offer not just a Store, they have a whole account system so users can have accounts and sites of their own. That is not something that we want to have, CraftingStore is a donation platform, not a CMS where you can create a forum, have accounts, etc. 

-Tim

**Comment by MODKILLER1001** [comment]
I was unaware of the ingame currency option, thank you!
