### ISSUE TITLE
Broken Grammar at the Checkout Page

### ISSUE THREAD

**Issue by itsWarHammer** [CraftingStore/Suggestions#651]
**Is your feature request related to a problem? Please describe.**
Broken grammar in the checkout tab at the bottom

"I agree with the I agree to the CraftingStore Terms Of Service and allow CraftingStore to process my data in this way, and hereby confirm that I'm over the age of 18, or have permission from my guardian."

**Describe the solution you'd like**
Change it to 
"I agree to the CraftingStore Terms Of Service and allow CraftingStore to process my data in this way, and hereby confirm that I'm over the age of 18, or have permission from my guardian."

**Additional context**
None

**Comment by thekdub** [comment]
Can confirm, this is due to the line
```
<input name="tos_cs" type="checkbox" required> I agree to the <a href="https://craftingstore.net/terms" target="_blank">{{ language.agreeCraftingStoreTos }}</a>
```
where `language.agreeCraftingStoreTos` is `I agree to the CraftingStore Terms Of Service and allow CraftingStore to process my data in this way, and hereby confirm that I'm over the age of 18, or have permission from my guardian.`, making the non-hyperlink text unnecessary.

**Comment by Tim-NL** [comment]
Hi,

This has been resolved, you may need to go to [ Webstore -> Languages ] and click "Update Language" to re-apply them to the store.

-Tim
