### ISSUE TITLE
Add custom pattern validation option to variables

### ISSUE THREAD

**Issue by thekdub** [CraftingStore/Suggestions#655]
**Is your feature request related to a problem? Please describe.**
Add a field to allow addition of custom regex pattern validation for variables, that way we can ensure the user entered valid input, e.g. proper formatting for a nickname or title.

**Describe the solution you'd like**
Add a field to the variable creation/edtiing page to allow entering a custom regex pattern for validation; then use that pattern for validating user input.

**Additional context**
None

**Comment by Tim-NL** [comment]
Hi,

Thank you for your suggestion. Unfortunately, we cannot safely allow you to use regex for the validation. We'd have to check what the user entered against your regex in our backend, and because Regex can be used to cause damage to our platform (by creating an infinite loop, or causing the backend language that we use to have a segmentation fault for example) we won't be able to allow user-generated regex.

Sorry about that.

-Tim

**Comment by thekdub** [comment]
Would it not be viable to instead do the pattern-checking on the client side?

Sure it would make it possible for a user to go bypass the check if they really wanted to, though I can't see much reason in why someone would want to do that, as giving invalid input would likely just result in the server rejecting their input.

Plus, doing the check client-side means no measurable additional load for the CraftingStore servers, and if someone were to put a harmful pattern in, the most it would do is cause the page to crash for the user on the specific store (and it'd be pretty silly to try crashing the page for your own users); all others would be unaffected.

**Comment by Tim-NL** [comment]
Hi,

We are not looking into doing it half-baked. Having client-side validation is not secure, and it would give store owners that do not know the difference between client and server-side a false sense of security, which can possibly lead to command injection in their console (e.g. giving a second argument or something like that by adding a space).

In the best scenario, it would indeed only cause the request to fail, but depending on how the regex was crafted, it may try to use up all memory and/or CPU.

I know that a store owner does not want to break their own store. I'm not talking about them; I'm talking about someone that will try to take down CraftingStore by creating a very heavy regex rule, that will loop. And then sending a DDoS attack that will do post requests to that specific endpoint. 

We are a pretty common target, we get DDoS attacks every day because taking down someone's store means taking down their income. So we are very careful about things like these, that might put our platform in danger of going down.

-Tim
