### ISSUE TITLE
Repeating background on the craftingstore site

### ISSUE THREAD

**Issue by KoltaiArmy** [CraftingStore/Suggestions#656]
**Describe the bug**
The background is repeating and not in fixed position on the craftingstore site.

**To Reproduce**
Scroll down on a webstore, and the background image is repeating

**Expected behavior**
As far as I remember, it was in fixed position, and if you scrolled down, the background was scrolled down too, and wasnt repeating 

**Screenshots**
![image](https://user-images.githubusercontent.com/36732586/150404089-226d61b2-7954-48a8-ad65-69b0a811460d.png)

**Platform**
Craftingstore website

**Additional context**
-

**Comment by Tim-NL** [comment]
Hi,

Did your store perhaps have a premium plan in the past? For those stores, that was indeed the case. We removed the templates on our caching servers for stores that no longer have an active template because there is no need for it. I just re-added the cover background back to those stores. 

-Tim
