### ISSUE TITLE
Custom Module Type

### ISSUE THREAD

**Issue by thekdub** [CraftingStore/Suggestions#690]
**Is your feature request related to a problem? Please describe.**
Currently, the module system is rather limited; you get to choose between recent payments, top customers, text, donation/community goals, gift card, server status, featured package, and discord modules, but there's no way to add your own if you'd like to accomplish something not present in this list.

**Describe the solution you'd like**
I'd like to see a 'custom' module type be added which allows you to use your own HTML/CSS/JS to build whatever functionality you might need into your webstore.

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

You can add custom modules using the HTML/CSS editor on our silver plan. We do not have an HTML module because that would allow someone to do custom HTML/CSS/JS without actually paying for that feature.

You can write pretty much any HTML/CSS/JS (or include external files) using the template editor, the modules are just included .twig files in the templates, so you can just add your custom code to the list.

-Tim
