### ISSUE TITLE
[Feature Request] Monthly subscriptions.

### ISSUE THREAD

**Issue by duhadventure** [CraftingStore/Suggestions#74]
**Is your feature request related to a problem? Please describe.**
I would like to create a monthly subscription that players can subscribe to, but that option does not exist.

**Describe the solution you'd like**
The ability to create a monthly subscription with packages.

**Comment by TheMonDon** [comment]
I would also like to see this as an option, kind of sad its been 4 months almost and there isn't an update on this request,

**Comment by Azorces** [comment]
The server I work for would love to be able to use a feature like this for some of our donator ranks.

**Comment by Blocksnmore** [comment]
It is possible just under your package options select one time payment with expiration and under commands make sure to set up the renewal and expiration commands

**Comment by Azorces** [comment]
Automatic subscriptions are not currently possible in crafting store Blocksnmore. Yes, they can buy a time-based package, but they cannot have it renew automatically.

**Comment by lackoSK** [comment]
Hello,

When is this a feature coming? I can see it's around 2 years since requested. Tebex already offers such a feature.

Regards,
lackoSK

**Comment by lackoSK** [comment]
@Tim-NL

**Comment by Tim-NL** [comment]
Please read the full overview page: https://github.com/CraftingStore/Suggestions/blob/master/README.md

We are working on subscription-based payments, and other features, so they will take time. If a request is added here, we will not start working on it directly in most cases. We keep them open if they are good feature requests so we can implement them at a later time. We have over 70 open requests at this moment and over 200 closed.

**Comment by Breakaway321** [comment]
Would love for this to be a feature. Kind of crazy to me that it's not already, tbh. I love CraftingStore but this feature is kind of huge for our server, so not having it is a big pain

**Comment by Scorpionvssub** [comment]
#SupportThisFeature

Been looking  into doing it but isnt really feasible this way i had in mind.
Hope it gets added!

**Comment by 2ic** [comment]
> Hello,
> When is this a feature coming? I can see it's around 2 years since requested. Tebex already offers such a feature.
> Regards,
> lackoSK

I migrated from Tebex a month ago (support issues) and been using their GIFT to another player for about a year: it's bugged like hell. Most often than not it was sending packages to a completely wrong steamID; that's when you managed for it to accept your friends name altogether. At the end Players had to enter friends steamID to be safe.

But yeah, I would love to have this feature on CraftingStore, that works.

**Comment by PiggiesGoSqueal** [comment]
I'd also like to see this.

**Comment by Sikatsu** [comment]
Please add this if you can <3

**Comment by WhenUHackUNoob** [comment]
We need this! We're are literally debating to switch to Tebex...

**Comment by Tim-NL** [comment]
Hi all,

What payment method(s) do you want to use subscriptions on? We cannot add it on all, but we can start with one gateway to create the integration.

-Tim

**Comment by TheMonDon** [comment]
> Hi all,
> 
> What payment method(s) do you want to use subscriptions on? We cannot add it on all, but we can start with one gateway to create the integration.
> 
> -Tim

PayPal.

**Comment by 2ic** [comment]
> 
> 
> Hi all,
> 
> What payment method(s) do you want to use subscriptions on? We cannot add it on all, but we can start with one gateway to create the integration.
> 
> -Tim

Paypal is the most used & requested.

**Comment by WhenUHackUNoob** [comment]
Yeah PayPal please.

**Comment by Villmarksjenta** [comment]
PayPal definitely!

**Comment by Tim-NL** [comment]
Hi,

Can anyone explain how this is handled on other store systems? The logic to support PayPal subscriptions is now added to our backend payment system after 6+ thousand new lines of code. So we can start to add it to CraftingStore. But we cannot really allow one of these to be added to the basket, I'm thinking of limiting the basket to just one item (just the subscription item) when it is added. If anyone has a link to a store that currently has subscriptions, then I'd love to know.

Thanks!

-Tim

**Comment by Sikatsu** [comment]
Hey Tim, my old store on Enjin is still up with subscriptions:

https://villagercraftold.enjin.com/

**Comment by Tim-NL** [comment]
Hi,

Thanks all!

We've just released the feature, but there are some caveats; 
- It only works with PayPal business accounts, because we're using their API for creating subscriptions. This is a new integration and will allow us to do more cool things in the future (Set-up guide: https://help.craftingstore.net/books/payment-gateways/page/how-to-set-up-paypal-using-the-api-business)
- The feature is for silver and up, it took many weeks, and lots of testing to complete. And we believe that it's a feature that is more "advanced", so the servers that require this should have the budget for it. It's not "enterprise" level, so we added it to the entry plan. Not any of the more expensive ones.
- It requires some templates changes if you are using a custom one (see: https://github.com/CraftingStore/Templates/commit/5277244614c7bb0bb2209e8e6502e237e14a7c16)

https://help.craftingstore.net/books/premium-features/page/subscription-support

Even tho we have tested the integration a lot, multiple times, on PayPal's sandbox and live system, there may be bugs, or unexpected edge cases (like; A client does not have enough money on their account). These aren't things that we can test. So please proceed with caution.

Thanks for the suggestion, it was a lot of work (weeks of pretty much full-time programming & testing) but due to the huge demand for it, and the age of this issue, we are happy to finally support subscriptions!

-Tim
