### ISSUE TITLE
Coupon Issue

### ISSUE THREAD

**Issue by Hipopotofobia** [CraftingStore/Suggestions#81]
When using a coupon in the store, it applies the coupon to every package in the basket. The only problem with that is when you have a coupon giveaway and you set it to say $5, it takes off $5 from every package instead of just subtracting $5 from the total. Also the % does the same, instead it should take a % off of the total. There is a way to only limit this to certain packages or categories, but when trying to do a giveaway, you don't want to limit what the user can get.

**Comment by Tim-NL** [comment]
This is expected behavior. If you buy two packages and apply the coupon code to them separately, it will discount them with 5$ each. As such, the system also works this way for multiple packages in the basket.

-Tim

**Comment by Hipopotofobia** [comment]
Yes but I have multiple packages on the store under $5, so they could add every package under $5 and get them all for free. If you set it to EX: 1 time use, that should not be possible

**Comment by Tim-NL** [comment]
Hi,

We added a new option for coupons: "Discount behaviour". You can set it to apply the discount to the basket total, instead of individual packages.

This will not show in the default templates just yet, the player will see the discounted price, but it will not be crossed out. We will update our default template later, as this is a pretty annoying bug, we needed to resolve it as soon as possible. 

-Tim
